
trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '1'
  Patch: '0'

steps:
- task : UseDotNet@2
  displayName: Use dotnet-sdk-5.0.100-preview.1.20155.7
  inputs:
        packageType: 'sdk'
        version: '5.0.100-preview.1.20155.7'

- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: Test projects
  inputs:
    command: 'test'
    
- task: DotNetCoreCLI@2
  displayName: Pack packages
  inputs:
    command: 'pack'
    configuration: $(buildConfiguration)
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: $(Major)
    minorVersion: $(Minor)
    patchVersion: $(Patch)

- task: PublishBuildArtifacts@1
  displayName: Push packages to drop
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-github-ci'
    publishLocation: 'Container'




